#!/usr/bin/env python3
"""Full DyNetAn network workflow for VarMDyn.

This script keeps trajectory-derived network analysis in one CLI:

  prepare  -> build stripped topology, sampled NetCDF, PDB, PSF, and DCD
  run      -> run DyNetAn and write top-node/top-edge tables
  compare  -> compare variant top-25 bottleneck residues against WT
  figures  -> build public summary figures from comparison tables
  render   -> render one WT-vs-variant comparison with PyMOL
  full     -> run prepare, run, compare, and optional render
"""

from __future__ import annotations

import argparse
import base64
import csv
import os
import re
import struct
import subprocess
import tempfile
from collections import Counter
from pathlib import Path

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[3]
_MDAN_OUTPUT_ROOT = os.environ.get("VARMDYN_MDAN_OUTPUT_ROOT")
_DEFAULT_DATA_ROOT = Path(_MDAN_OUTPUT_ROOT).expanduser() / "network" if _MDAN_OUTPUT_ROOT else REPO_ROOT / "data" / "mdan" / "network"
DATA_ROOT = Path(os.environ.get("VARMDYN_NETWORK_DATA_ROOT", _DEFAULT_DATA_ROOT)).expanduser()
RUN_ROOT = Path(os.environ.get("VARMDYN_NETWORK_RUN_ROOT", DATA_ROOT / "runs")).expanduser()
SCRIPT_DIR = Path(__file__).resolve().parent
LAST_HPC_JOB_FILE = REPO_ROOT / ".last_network_hpc_job_id"
SEL_RESID_RE = re.compile(r"resid\s+(\d+)")
PROTEIN_WHEAT_RGB = np.array([245, 222, 179], dtype=np.float32)
WHITE_RGB = np.array([255, 255, 255], dtype=np.float32)

AA3_TO_1 = {
    "ALA": "A",
    "ARG": "R",
    "ASN": "N",
    "ASP": "D",
    "CYS": "C",
    "GLU": "E",
    "GLN": "Q",
    "GLY": "G",
    "HIS": "H",
    "HID": "H",
    "HIE": "H",
    "HIP": "H",
    "ILE": "I",
    "LEU": "L",
    "LYS": "K",
    "MET": "M",
    "PHE": "F",
    "PRO": "P",
    "SER": "S",
    "THR": "T",
    "TRP": "W",
    "TYR": "Y",
    "VAL": "V",
}


def run_command(cmd: list[str], log: Path | None = None) -> None:
    if log is None:
        subprocess.run(cmd, check=True)
        return
    log.parent.mkdir(parents=True, exist_ok=True)
    with log.open("w", encoding="utf-8") as handle:
        proc = subprocess.run(cmd, stdout=handle, stderr=handle)
    if proc.returncode:
        raise SystemExit(f"command failed; see {log}: {' '.join(cmd)}")


def run_cpptraj(input_text: str, log: Path) -> None:
    log.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", suffix=".in", prefix="varmdyn_cpptraj_", delete=False) as handle:
        handle.write(input_text)
        input_path = Path(handle.name)
    try:
        with log.open("w", encoding="utf-8") as out:
            out.write("# cpptraj input generated by workflows/mdan/network/network.py\n")
            out.write("# The durable workflow script stays under workflows/; this input file is transient.\n")
            out.write(input_text)
            out.write("\n# cpptraj output\n")
            proc = subprocess.run(["cpptraj", "-i", str(input_path)], stdout=out, stderr=out)
        if proc.returncode:
            raise SystemExit(f"cpptraj failed; see {log}")
    finally:
        try:
            input_path.unlink()
        except FileNotFoundError:
            pass


def csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def split_variants(value: str) -> list[str]:
    return [item.strip() for item in re.split(r"[,:]", value) if item.strip()]


def slurm_list_value(value: str) -> str:
    """Encode list-like values safely for Slurm --export, which uses commas."""
    return ":".join(split_variants(value))


def variants_arg_requests_all(value: str | None) -> bool:
    return not value or value.strip().lower() in {"all", "*"}


def discover_variants(root: Path, wt: str) -> list[str]:
    skip = {"variants", "logs", "all", "*"}
    variants = sorted(
        path.name
        for path in root.iterdir()
        if path.is_dir() and path.name not in skip and not any(ch in path.name for ch in "*?[]")
    )
    if wt in variants:
        variants = [wt] + [variant for variant in variants if variant != wt]
    return variants


def resolve_variants(args: argparse.Namespace) -> list[str]:
    if args.variants and not variants_arg_requests_all(args.variants):
        return split_variants(args.variants)
    root = Path(args.root).expanduser()
    variants = discover_variants(root, args.wt)
    topology_suffix = getattr(args, "topology_suffix", "")
    if topology_suffix:
        variants = [variant for variant in variants if (root / variant / topology_suffix).exists()]
    if not variants:
        raise SystemExit(f"no variant folders found in {args.root}")
    return variants


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def prepare_variant(args: argparse.Namespace, variant: str) -> None:
    try:
        import MDAnalysis as mda
        import parmed as pmd
        from MDAnalysis.coordinates.DCD import DCDWriter
    except ImportError as exc:
        raise SystemExit(
            "Missing MD preparation dependency. Activate varmdyn_dynetan first. "
            f"Original error: {exc}"
        ) from exc

    src = Path(args.root).expanduser() / variant
    topo = src / args.topology_suffix
    if not topo.exists():
        raise SystemExit(f"missing topology for {variant}: {topo}")

    out = DATA_ROOT / "prepared" / args.state / variant
    work = RUN_ROOT / "cpptraj" / args.state / variant
    out.mkdir(parents=True, exist_ok=True)
    work.mkdir(parents=True, exist_ok=True)

    keep = args.state == "holo"
    tag = "keepATPmg" if keep else "striped"
    topo_out = out / f"{variant}.{tag}.prmtop"
    nc_out = out / f"{variant}.concatenated_750frames.{tag}.nc"
    pdb_out = out / f"{variant}.pdb"
    psf_out = out / f"{variant}.psf"
    dcd_out = out / f"{variant}.dcd"
    strip_mask = args.holo_strip_mask if keep else args.apo_strip_mask

    if not topo_out.exists() or args.force:
        run_cpptraj(
            f"parm {topo}\nparmstrip '{strip_mask}'\nparmwrite out {topo_out}\ngo\nquit\n",
            work / "strip_topology.log",
        )

    trajin_lines: list[str] = []
    for rep in split_variants(args.replicas):
        for chunk in split_variants(args.chunks):
            nc = src / args.traj_template.format(replica=rep, chunk=chunk)
            if nc.exists():
                trajin_lines.append(f"trajin {nc} 1 last {args.stride}")
            elif args.strict:
                raise SystemExit(f"missing trajectory chunk for {variant}: {nc}")
            else:
                print(f"[WARN] missing trajectory chunk for {variant}: {nc}")
    if not trajin_lines:
        raise SystemExit(f"no trajectory chunks found for {variant}")

    regenerate_nc = args.force or not nc_out.exists()
    if nc_out.exists() and not regenerate_nc and args.min_prepared_frames > 0:
        try:
            existing_frames = len(mda.Universe(str(topo_out), str(nc_out)).trajectory)
        except Exception:
            existing_frames = 0
        if existing_frames < args.min_prepared_frames:
            print(
                f"[WARN] regenerating short prepared trajectory for {args.state}/{variant}: "
                f"{nc_out} has {existing_frames} frames; expected at least {args.min_prepared_frames}"
            )
            regenerate_nc = True

    if regenerate_nc:
        run_cpptraj(
            "parm {topo}\n{trajin}\nautoimage\nstrip '{strip}'\ntrajout {out} netcdf\ngo\nquit\n".format(
                topo=topo,
                trajin="\n".join(trajin_lines),
                strip=strip_mask,
                out=nc_out,
            ),
            work / "concat_sample.log",
        )

    if not psf_out.exists() or args.force:
        st = pmd.load_file(str(topo_out))
        for residue in st.residues:
            residue.segid = "PROT"
        st.save(str(psf_out), overwrite=True)

    regenerate_dcd = args.force or not dcd_out.exists()
    if dcd_out.exists() and not regenerate_dcd and args.min_prepared_frames > 0:
        existing_dcd_frames = len(mda.Universe(str(psf_out), str(dcd_out)).trajectory)
        if existing_dcd_frames < args.min_prepared_frames:
            print(
                f"[WARN] regenerating short prepared DCD for {args.state}/{variant}: "
                f"{dcd_out} has {existing_dcd_frames} frames; expected at least {args.min_prepared_frames}"
            )
            regenerate_dcd = True

    if not pdb_out.exists() or regenerate_dcd or args.force:
        u = mda.Universe(str(topo_out), str(nc_out))
        if not pdb_out.exists() or args.force:
            u.trajectory[0]
            u.atoms.write(str(pdb_out))
        if regenerate_dcd:
            with DCDWriter(str(dcd_out), u.atoms.n_atoms) as writer:
                for _ts in u.trajectory:
                    writer.write(u.atoms)

    print(f"[OK] prepared {args.state}/{variant}: {out}")


def selection_label(node: int, nodes_atm_sel) -> str:
    atom = nodes_atm_sel[node]
    return f"resname {atom.resname} and resid {atom.resid}"


def run_dynetan_variant(args: argparse.Namespace, variant: str) -> None:
    try:
        import dynetan as dna
        import MDAnalysis as mda
        import networkx as nx
    except ImportError as exc:
        raise SystemExit(f"Missing dynetan. Activate varmdyn_dynetan first. Original error: {exc}") from exc

    stage_tag = args.stage_tag or f"varmdyn_full_{args.state}"
    prepared = DATA_ROOT / "prepared" / args.state / variant
    psf = prepared / f"{variant}.psf"
    dcd = prepared / f"{variant}.dcd"
    if not psf.exists() or not dcd.exists():
        raise SystemExit(f"missing prepared inputs for {args.state}/{variant}: {prepared}")
    frame_count = len(mda.Universe(str(psf), str(dcd)).trajectory)
    sampled_frames = min(args.num_sampled_frames, max(1, frame_count - 1))
    if sampled_frames != args.num_sampled_frames:
        message = (
            f"requested {args.num_sampled_frames} sampled frames but {dcd} has {frame_count}; "
            f"need at least {args.num_sampled_frames + 1} frames for this run"
        )
        if not args.allow_short_sample:
            raise SystemExit(f"{message}. Use --allow-short-sample only for smoke testing.")
        print(f"[WARN] {message}; using {sampled_frames} for smoke testing.")

    out = DATA_ROOT / "dynetan" / args.state / variant
    done = out / f"bottleneck_nodes_top{args.top_nodes}_{stage_tag}.csv"
    if done.exists() and not args.force:
        print(f"[OK] DyNetAn already complete: {args.state}/{variant} ({done})")
        return
    out.mkdir(parents=True, exist_ok=True)

    dnap = dna.proctraj.DNAproc()
    dnap.setNumWinds(args.num_winds)
    dnap.setNumSampledFrames(sampled_frames)
    dnap.setCutoffDist(args.cutoff)
    dnap.setContactPersistence(args.contact_persistence)
    dnap.setSegIDs(["PROT"])
    if hasattr(dnap, "setSolvNames"):
        dnap.setSolvNames(["WAT", "TIP3", "HOH", "OPC"])
    else:
        dnap.h2oName = ["WAT", "TIP3", "HOH", "OPC"]

    dnap.loadSystem(str(psf), [str(dcd)])
    dnap.checkSystem()
    if not getattr(dnap, "notSelSegidSet", None):
        dnap.notSelSegidSet = ["__VARMDYN_NO_NONSELECTED_SEGID__"]
    dnap.selectSystem(withSolvent=False)
    dnap.prepareNetwork()
    dnap.alignTraj(inMemory=False)
    dnap.findContacts(stride=1)
    dnap.filterContacts(notSameRes=True, notConsecutiveRes=True, removeIsolatedNodes=True)
    dnap.calcCor(ncores=args.ncores)
    dnap.calcCartesian(backend=args.cartesian_backend)
    dnap.calcGraphInfo()
    dnap.calcBetween(ncores=args.ncores)
    dnap.calcEigenCentral()
    dnap.calcCommunities()
    if getattr(dnap, "distsAll", None) is None:
        dnap.distsAll = np.zeros((1, 1), dtype=np.float64)
    dnap.saveData(str(out / f"dnaData_{stage_tag}"))

    graph = dnap.nxGraphs[0]
    node_rows = [
        {
            "Node": node,
            "Degree": graph.nodes[node].get("degree", None),
            "Eigenvector": graph.nodes[node].get("eigenvector", None),
            "Selection": selection_label(node, dnap.nodesAtmSel),
        }
        for node in graph.nodes
    ]
    degree_rows = sorted(node_rows, key=lambda row: float(row["Degree"] or 0.0), reverse=True)[
        : args.top_nodes
    ]
    eigen_rows = sorted(node_rows, key=lambda row: float(row["Eigenvector"] or 0.0), reverse=True)[
        : args.top_nodes
    ]
    write_csv(out / f"top_degree_nodes_top{args.top_nodes}_{stage_tag}.csv", degree_rows, ["Node", "Degree", "Eigenvector", "Selection"])
    write_csv(out / "top_degree_nodes_top25.csv", degree_rows, ["Node", "Degree", "Eigenvector", "Selection"])
    write_csv(out / f"top_eigenvector_nodes_top{args.top_nodes}_{stage_tag}.csv", eigen_rows, ["Node", "Degree", "Eigenvector", "Selection"])

    node_betweenness = {node: 0.0 for node in graph.nodes}
    for (i, j), value in dnap.btws[0].items():
        node_betweenness[i] = node_betweenness.get(i, 0.0) + float(value)
        node_betweenness[j] = node_betweenness.get(j, 0.0) + float(value)
    top_bottleneck = sorted(node_betweenness.items(), key=lambda item: item[1], reverse=True)[
        : args.top_nodes
    ]
    bottleneck_rows = [
        {
            "Node": node,
            "BottleneckScore_sumEdgeBetw": f"{score:.8f}",
            "Degree": graph.nodes[node].get("degree", None),
            "Eigenvector": graph.nodes[node].get("eigenvector", None),
            "Selection": selection_label(node, dnap.nodesAtmSel),
        }
        for node, score in top_bottleneck
    ]
    write_csv(out / f"bottleneck_nodes_top{args.top_nodes}_{stage_tag}.csv", bottleneck_rows, ["Node", "BottleneckScore_sumEdgeBetw", "Degree", "Eigenvector", "Selection"])
    write_csv(out / "bottleneck_nodes_top25.csv", bottleneck_rows, ["Node", "BottleneckScore_sumEdgeBetw", "Degree", "Eigenvector", "Selection"])

    with (out / f"bottleneck_nodes_top{args.top_nodes}_{stage_tag}.txt").open("w", encoding="utf-8") as handle:
        handle.write(f"Top {args.top_nodes} Bottleneck Nodes (sum of incident edge betweenness)\n")
        handle.write(f"Stage: {stage_tag}\n")
        handle.write("Rank\tNode\tBottleneckScore\tDegree\tEigenvector\tSelection\n")
        for rank, (node, score) in enumerate(top_bottleneck, start=1):
            handle.write(
                f"{rank}\t{node}\t{score}\t{graph.nodes[node].get('degree', None)}\t"
                f"{graph.nodes[node].get('eigenvector', None)}\t{selection_label(node, dnap.nodesAtmSel)}\n"
            )

    edge_rows = [
        {
            "Edge_i": i,
            "Edge_j": j,
            "EdgeBetweenness": f"{float(value):.8f}",
            "Correlation": f"{float(dnap.corrMatAll[0, i, j]):.8f}",
            "Sel_i": selection_label(i, dnap.nodesAtmSel),
            "Sel_j": selection_label(j, dnap.nodesAtmSel),
        }
        for (i, j), value in dnap.btws[0].items()
    ]
    edge_rows = sorted(edge_rows, key=lambda row: float(row["EdgeBetweenness"]), reverse=True)[
        : args.top_edges
    ]
    write_csv(out / f"top_edges_betweenness_top{args.top_edges}_{stage_tag}.csv", edge_rows, ["Edge_i", "Edge_j", "EdgeBetweenness", "Correlation", "Sel_i", "Sel_j"])

    with (out / f"network_report_{stage_tag}.txt").open("w", encoding="utf-8") as handle:
        handle.write("CDKL5 DyNetAn Network Report\n")
        handle.write("========================================\n\n")
        handle.write(f"Variant: {variant}\nMode   : concatenated\nStage  : {stage_tag}\n\n")
        handle.write(f"Nodes: {len(graph.nodes)}\nEdges: {len(graph.edges)}\n")
        handle.write(f"Density: {nx.density(graph):.4f}\n")
        handle.write(f"Transitivity: {nx.transitivity(graph):.4f}\n")
        handle.write(f"Connected components: {nx.number_connected_components(graph)}\n")
        handle.write(f"Largest component size: {len(max(nx.connected_components(graph), key=len))}\n")
    print(f"[OK] DyNetAn complete: {out}")


def residue_label(selection: str) -> str:
    match = re.search(r"\bresname\s+(\S+)\s+and\s+resid\s+(\d+)\b", selection)
    if not match:
        raise ValueError(f"could not parse selection: {selection}")
    resname, resid = match.group(1), int(match.group(2))
    return f"{AA3_TO_1.get(resname.upper(), resname[0].upper())}{resid}"


def residue_number(label: str) -> int:
    match = re.search(r"(\d+)$", label)
    if not match:
        raise ValueError(f"could not parse residue number: {label}")
    return int(match.group(1))


def compare_top25(args: argparse.Namespace) -> None:
    stage_tag = args.stage_tag or f"varmdyn_full_{args.state}"
    variants = resolve_variants(args)
    sets: dict[str, set[str]] = {}
    for variant in variants:
        folder = DATA_ROOT / "dynetan" / args.state / variant
        path = folder / f"bottleneck_nodes_top25_{stage_tag}.csv"
        if not path.exists():
            path = folder / "bottleneck_nodes_top25.csv"
        sets[variant] = {residue_label(row["Selection"]) for row in csv_rows(path)}

    wt_set = sets[args.wt]
    out = DATA_ROOT / "compare" / args.state
    overlap_rows = []
    transition_rows = []
    frequency = {"wt_lost": Counter(), "gained": Counter()}
    mutant_variants = [variant for variant in variants if variant != args.wt]

    for variant in mutant_variants:
        residues = sets[variant]
        shared = wt_set & residues
        wt_lost = wt_set - residues
        gained = residues - wt_set
        overlap_rows.append(
            {
                "variant": variant,
                "wt_top_total": len(wt_set),
                "shared": len(shared),
                "shared_fraction": f"{len(shared) / len(wt_set):.4f}",
                "wt_lost": len(wt_lost),
                "gained": len(gained),
            }
        )
        for klass, labels in [("shared", shared), ("wt_lost", wt_lost), ("gained", gained)]:
            for label in sorted(labels, key=residue_number):
                transition_rows.append(
                    {
                        "state": args.state,
                        "variant": variant,
                        "transition_class": klass,
                        "residue": label,
                        "residue_number": residue_number(label),
                    }
                )
        frequency["wt_lost"].update(wt_lost)
        frequency["gained"].update(gained)

    freq_rows = []
    for klass in ["wt_lost", "gained"]:
        for residue, count in sorted(
            frequency[klass].items(), key=lambda item: (-item[1], residue_number(item[0]), item[0])
        ):
            freq_rows.append(
                {
                    "state": args.state,
                    "transition_class": klass,
                    "residue": residue,
                    "count": count,
                    "total_variants": len(mutant_variants),
                }
            )

    write_csv(out / "overlap_with_WT.csv", overlap_rows, ["variant", "wt_top_total", "shared", "shared_fraction", "wt_lost", "gained"])
    write_csv(out / "wt_vs_variants_lost_gained.csv", transition_rows, ["state", "variant", "transition_class", "residue", "residue_number"])
    write_csv(out / "transition_frequency.csv", freq_rows, ["state", "transition_class", "residue", "count", "total_variants"])
    print(f"[OK] comparison tables: {out}")


def require_file(path: Path, label: str) -> Path:
    if not path.is_file():
        raise SystemExit(f"missing {label}: {path}")
    return path


def save_figure(fig, out_base: Path) -> None:
    out_base.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_base.with_suffix(".png"), dpi=300, bbox_inches="tight")
    fig.savefig(out_base.with_suffix(".svg"), bbox_inches="tight")


def configure_matplotlib_cache() -> None:
    cache = Path(os.environ.get("MPLCONFIGDIR", REPO_ROOT / "data" / ".cache" / "matplotlib"))
    cache.mkdir(parents=True, exist_ok=True)
    os.environ.setdefault("MPLCONFIGDIR", str(cache))


def plot_overlap_state(state: str, out_dir: Path) -> list[Path]:
    configure_matplotlib_cache()
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise SystemExit(f"missing matplotlib for network figures: {exc}") from exc

    table = require_file(DATA_ROOT / "compare" / state / "overlap_with_WT.csv", f"{state} overlap table")
    rows = csv_rows(table)
    if not rows:
        raise SystemExit(f"empty {state} overlap table: {table}")
    variants = [row["variant"] for row in rows]
    shared = [int(float(row["shared"])) for row in rows]
    wt_lost = [int(float(row["wt_lost"])) for row in rows]
    gained = [int(float(row["gained"])) for row in rows]

    fig, ax = plt.subplots(figsize=(max(6.0, len(variants) * 0.9), 4.2))
    x = list(range(len(variants)))
    ax.bar(x, shared, label="Shared with WT", color="#4C956C")
    ax.bar(x, wt_lost, bottom=shared, label="WT lost", color="#2C5AA0")
    ax.bar(
        x,
        gained,
        bottom=[a + b for a, b in zip(shared, wt_lost)],
        label="Variant gained",
        color="#D97904",
    )
    ax.set_title(f"{state.upper()} WT top-25 bottleneck overlap")
    ax.set_ylabel("Residue count")
    ax.set_xticks(x)
    ax.set_xticklabels(variants, rotation=35, ha="right")
    ax.set_ylim(0, max([a + b + c for a, b, c in zip(shared, wt_lost, gained)] + [25]) + 2)
    ax.legend(frameon=False, ncols=3, loc="upper center", bbox_to_anchor=(0.5, 1.18))
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    out_base = out_dir / f"{state}_wt_overlap"
    save_figure(fig, out_base)
    plt.close(fig)
    return [out_base.with_suffix(".png"), out_base.with_suffix(".svg")]


def plot_transition_frequency_state(state: str, out_dir: Path, top_n: int) -> list[Path]:
    configure_matplotlib_cache()
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise SystemExit(f"missing matplotlib for network figures: {exc}") from exc

    table = require_file(DATA_ROOT / "compare" / state / "transition_frequency.csv", f"{state} transition-frequency table")
    rows = csv_rows(table)
    if not rows:
        raise SystemExit(f"empty {state} transition-frequency table: {table}")

    lost = [row for row in rows if row["transition_class"] == "wt_lost"][:top_n]
    gained = [row for row in rows if row["transition_class"] == "gained"][:top_n]
    labels = [row["residue"] for row in lost] + [row["residue"] for row in gained]
    values = [-int(row["count"]) for row in lost] + [int(row["count"]) for row in gained]
    colors = ["#2C5AA0"] * len(lost) + ["#D97904"] * len(gained)
    y = list(range(len(labels)))

    fig_height = max(4.2, len(labels) * 0.28)
    fig, ax = plt.subplots(figsize=(7.2, fig_height))
    ax.barh(y, values, color=colors)
    ax.axvline(0, color="#333333", linewidth=0.8)
    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.invert_yaxis()
    ax.set_xlabel("Variant count; WT lost left, gained right")
    ax.set_title(f"{state.upper()} recurrent network residue changes")
    max_count = max(abs(value) for value in values) if values else 1
    ax.set_xlim(-(max_count + 1), max_count + 1)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    out_base = out_dir / f"{state}_transition_frequency"
    save_figure(fig, out_base)
    plt.close(fig)
    return [out_base.with_suffix(".png"), out_base.with_suffix(".svg")]


def build_figures(args: argparse.Namespace) -> None:
    states = ["apo", "holo"] if args.state == "all" else [args.state]
    out_dir = (Path(args.outdir).expanduser() if args.outdir else DATA_ROOT / "figures").resolve()
    written: list[Path] = []
    for state in states:
        written += plot_overlap_state(state, out_dir)
        written += plot_transition_frequency_state(state, out_dir, args.top_n)
        if not args.summary_only:
            written += build_pathway_renders_state(state, out_dir, args)
    if not args.summary_only and args.state == "all":
        written += compose_network_pathway_preview(out_dir)
        written += build_residue_remodel_figure(args, out_dir)
    for path in written:
        print(f"[OK] figure: {path}")


def numbered_variant(variant: str) -> str:
    order = ["WT", "L119R", "D193H", "G202E", "Q219K", "C291Y"]
    if variant in order:
        return f"{order.index(variant) + 1:02d}_{variant}"
    return variant


def display_variant(variant: str) -> str:
    return variant.split("_", 1)[1] if re.match(r"^\d\d_", variant) else variant


def read_bottleneck_residues(path: Path, top_n: int) -> list[int]:
    residues: list[int] = []
    for row in csv_rows(path):
        if len(residues) >= top_n:
            break
        selection = row.get("Selection", "")
        match = SEL_RESID_RE.search(selection)
        if match:
            residues.append(int(match.group(1)))
            continue
        value = row.get("residue_number", "") or row.get("ResidueNumber", "")
        if value:
            residues.append(int(float(value)))
    seen: set[int] = set()
    ordered: list[int] = []
    for residue in residues:
        if residue not in seen:
            seen.add(residue)
            ordered.append(residue)
    return ordered


def write_pathway_pml(
    pml_path: Path,
    pdb_path: Path,
    common: list[int],
    wt_lost: list[int],
    gained: list[int],
    png_path: Path,
) -> None:
    def fmt(values: list[int]) -> str:
        return ", ".join(str(value) for value in values)

    write_text(
        pml_path,
        f"""
load {pdb_path.as_posix()}, cdl

set bg_rgb, white
hide everything
show cartoon, cdl and polymer.protein
color gray90, cdl and polymer.protein
set cartoon_transparency, 0.70, cdl and polymer.protein

python
from pymol import cmd
from pymol.cgo import BEGIN, LINES, VERTEX, END, COLOR

SPHERE_SCALE = 0.55
LINE_ALPHA = 0.55
LINE_WIDTH = 2

COMMON = [{fmt(common)}]
WT_LOST = [{fmt(wt_lost)}]
GAIN = [{fmt(gained)}]

def _show(name, residues, color):
    cmd.delete(name)
    if not residues:
        return
    cmd.select(name, "cdl and polymer.protein and name CA and (resi " + "+".join(map(str, residues)) + ")")
    cmd.show("spheres", name)
    cmd.set("sphere_scale", SPHERE_SCALE, name)
    cmd.color(color, name)

def _line(name, residues, rgb):
    cmd.delete(name)
    if len(residues) < 2:
        return
    coords = []
    for residue in residues:
        sel = f"cdl and polymer.protein and resi {{residue}} and name CA"
        if cmd.count_atoms(sel):
            coords.append(cmd.get_atom_coords(sel))
    if len(coords) < 2:
        return
    cgo = [BEGIN, LINES, COLOR, rgb[0], rgb[1], rgb[2]]
    for a, b in zip(coords[:-1], coords[1:]):
        cgo += [VERTEX, *a, VERTEX, *b]
    cgo += [END]
    cmd.load_cgo(cgo, name)
    cmd.set("cgo_line_width", LINE_WIDTH, name)
    cmd.set("cgo_transparency", LINE_ALPHA, name)

_show("common_res", COMMON, "green")
_show("wt_lost_res", WT_LOST, "blue")
_show("gain_res", GAIN, "orange")
_line("line_common", COMMON, (0.10, 0.45, 0.10))
_line("line_gain", GAIN, (0.90, 0.55, 0.05))

cmd.set_view((
    0.8545376658439636, 0.46188580989837646, 0.23754343390464783,
    -0.24071544408798218, 0.7574628591537476, -0.6068824529647827,
    -0.4602406919002533, 0.46142351627349854, 0.7584635019302368,
    0.0, 0.0, -262.4645690917969,
    44.75941848754883, 32.431861877441406, 65.35641479492188,
    206.92906188964844, 318.00006103515625, -20.0
))
cmd.turn("z", 90)
cmd.zoom("cdl", 7)
python end

png {png_path.as_posix()}, width=1400, height=1200, dpi=300, ray=1
quit
""".strip()
        + "\n",
    )


def build_pathway_renders_state(state: str, out_dir: Path, args: argparse.Namespace) -> list[Path]:
    if not shutil_which("pymol"):
        print("[INFO] pymol not found; skipping pathway renders.")
        return []

    variants = [args.wt] + [variant for variant in split_variants(args.variants) if variant != args.wt]
    dynetan_root = DATA_ROOT / "dynetan" / state
    prepared_root = DATA_ROOT / "prepared" / state
    state_dir = out_dir / "pathway_renders" / state
    scripts_dir = RUN_ROOT / "pymol" / state
    renders_dir = state_dir / "renders"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    renders_dir.mkdir(parents=True, exist_ok=True)

    variant_to_residues: dict[str, list[int]] = {}
    for variant in variants:
        table = require_file(dynetan_root / variant / "bottleneck_nodes_top25.csv", f"{state}/{variant} bottleneck table")
        variant_to_residues[variant] = read_bottleneck_residues(table, args.pathway_top_n)

    wt_residues = variant_to_residues[args.wt]
    wt_set = set(wt_residues)
    written: list[Path] = []
    for variant in variants:
        residues = variant_to_residues[variant]
        residue_set = set(residues)
        common = [residue for residue in residues if residue in wt_set]
        gained = [residue for residue in residues if residue not in wt_set]
        wt_lost = [residue for residue in wt_residues if residue not in residue_set]
        pdb_path = require_file(prepared_root / variant / f"{variant}.pdb", f"{state}/{variant} render PDB")
        numbered = numbered_variant(variant)
        pml_path = scripts_dir / f"make_pathway_{numbered}_{state}.pml"
        png_path = renders_dir / f"pathway_{numbered}_{state}.png"
        if args.force_pathways or not png_path.exists():
            write_pathway_pml(pml_path, pdb_path, common, wt_lost, gained, png_path)
            run_command(["pymol", "-cq", str(pml_path)])
        written.append(png_path)

    panel_png, panel_jpg = compose_state_pathway_panel(state, renders_dir, state_dir)
    written.extend([panel_png, panel_jpg])
    return written


def crop_white_image(img, pad: int = 4):
    from PIL import ImageOps

    arr = np.array(img.convert("RGB"))
    mask = np.any(arr < 242, axis=2)
    h, _w = mask.shape
    mask[int(h * 0.90) :, :] = False
    if not mask.any():
        return img
    ys, xs = np.where(mask)
    y0, y1 = int(ys.min()), int(ys.max()) + 1
    x0, x1 = int(xs.min()), int(xs.max()) + 1
    cropped = img.crop((max(0, x0 - pad), max(0, y0 - pad), min(arr.shape[1], x1 + pad), min(arr.shape[0], y1 + pad)))
    return ImageOps.expand(apply_dynamics_protein_style(cropped.convert("RGB")), border=18, fill="white")


def apply_dynamics_protein_style(img):
    """Fade protein while preserving network marks."""
    from PIL import Image

    arr = np.array(img.convert("RGB"), dtype=np.float32)
    channel_range = arr.max(axis=2) - arr.min(axis=2)
    nonwhite = np.any(arr < 246, axis=2)
    protein_mask = nonwhite & (channel_range < 42)
    styled = arr.copy()
    protein = styled[protein_mask]
    if protein.size:
        wheat_tinted = 0.25 * protein + 0.75 * PROTEIN_WHEAT_RGB
        styled[protein_mask] = 0.58 * wheat_tinted + 0.42 * WHITE_RGB
    return Image.fromarray(np.clip(styled, 0, 255).astype(np.uint8), mode="RGB")


def compose_state_pathway_panel(state: str, renders_dir: Path, out_dir: Path) -> tuple[Path, Path]:
    configure_matplotlib_cache()
    try:
        import matplotlib.pyplot as plt
        from matplotlib.lines import Line2D
        from PIL import Image
    except ImportError as exc:
        raise SystemExit(f"missing figure dependency for pathway panel: {exc}") from exc

    variants = ["WT", "L119R", "D193H", "G202E", "Q219K", "C291Y"]
    fig, axes = plt.subplots(3, 2, figsize=(8.2, 10.8), dpi=300)
    for ax, variant in zip(axes.flatten(), variants):
        numbered = numbered_variant(variant)
        image = Image.open(renders_dir / f"pathway_{numbered}_{state}.png")
        ax.imshow(crop_white_image(image))
        ax.axis("off")
        ax.text(0.5, -0.02, variant, transform=ax.transAxes, ha="center", va="top", fontsize=12, clip_on=False)

    handles = [
        Line2D([0], [0], marker="o", markersize=7, linestyle="None", markerfacecolor="#16c34a", markeredgecolor="#16c34a", label="conserved"),
        Line2D([0], [0], marker="o", markersize=7, linestyle="None", markerfacecolor="#3b39d8", markeredgecolor="#3b39d8", label="WT-lost"),
        Line2D([0], [0], marker="o", markersize=7, linestyle="None", markerfacecolor="#f28e1c", markeredgecolor="#f28e1c", label="variant-gained"),
    ]
    fig.legend(handles=handles, loc="upper center", bbox_to_anchor=(0.5, 0.993), frameon=False, ncol=3, columnspacing=1.1, handletextpad=0.4, fontsize=12)
    plt.subplots_adjust(left=0.003, right=0.997, top=0.965, bottom=0.07, wspace=0.0, hspace=0.12)
    panel_png = out_dir / f"network_pathway_{state}_panel.png"
    panel_jpg = out_dir / f"network_pathway_{state}_panel.jpg"
    fig.savefig(panel_png, dpi=300)
    fig.savefig(panel_jpg, dpi=300)
    plt.close(fig)
    return panel_png, panel_jpg


def paste_centered(canvas, image, box: tuple[int, int, int, int]) -> None:
    x0, y0, x1, y1 = box
    box_w = x1 - x0
    box_h = y1 - y0
    scale = min(box_w / image.width, box_h / image.height)
    new_size = (max(1, round(image.width * scale)), max(1, round(image.height * scale)))
    resampling = getattr(image, "Resampling", None)
    resized = image.resize(new_size, resampling.LANCZOS if resampling else 1)
    canvas.paste(resized, (x0 + (box_w - resized.width) // 2, y0 + (box_h - resized.height) // 2))


def compose_network_pathway_preview(out_dir: Path) -> list[Path]:
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError as exc:
        raise SystemExit(f"missing PIL for network pathway preview: {exc}") from exc

    variants = ["WT", "L119R", "D193H", "G202E", "Q219K", "C291Y"]
    width, height = 3052, 1520
    margin_x = 34
    panel_gap = 26
    legend_h = 112
    bottom_label_h = 72
    state_header_h = 44
    tile_w = (width - 2 * margin_x - 5 * panel_gap) // 6
    tile_h = (height - legend_h - bottom_label_h - 2 * state_header_h) // 2
    canvas = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(canvas)

    font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    label_font = ImageFont.truetype(font_path, 42)
    legend_font = ImageFont.truetype(font_path, 44)
    panel_font = ImageFont.truetype(font_path, 48)

    def text_center(box: tuple[int, int, int, int], text: str, font) -> None:
        x0, y0, x1, y1 = box
        bbox = draw.textbbox((0, 0), text, font=font)
        x = x0 + (x1 - x0 - (bbox[2] - bbox[0])) / 2
        y = y0 + (y1 - y0 - (bbox[3] - bbox[1])) / 2 - bbox[1]
        draw.text((x, y), text, font=font, fill="black")

    for state_index, (state, panel_letter) in enumerate([("apo", "A"), ("holo", "B")]):
        header_y = legend_h + state_index * (state_header_h + tile_h)
        draw.text((14, header_y + 2), panel_letter, font=panel_font, fill="black")
        renders_dir = out_dir / "pathway_renders" / state / "renders"
        for col, variant in enumerate(variants):
            numbered = numbered_variant(variant)
            image = Image.open(renders_dir / f"pathway_{numbered}_{state}.png")
            cropped = crop_white_image(image)
            x0 = margin_x + col * (tile_w + panel_gap)
            y0 = legend_h + state_index * (state_header_h + tile_h) + state_header_h
            paste_centered(canvas, cropped, (x0 + 10, y0 + 8, x0 + tile_w - 10, y0 + tile_h - 8))

    label_y0 = height - bottom_label_h
    for col, variant in enumerate(variants):
        x0 = margin_x + col * (tile_w + panel_gap)
        text_center((x0, label_y0, x0 + tile_w, height), variant, label_font)

    start_x = width // 2 - 385 * 3 // 2
    legend_y = 60
    for i, (color, label) in enumerate([("#16c34a", "conserved"), ("#3b39d8", "WT-lost"), ("#f28e1c", "gained")]):
        x = start_x + i * 385
        draw.ellipse((x, legend_y - 12, x + 24, legend_y + 12), fill=color, outline=color)
        draw.text((x + 40, legend_y - 27), label, font=legend_font, fill="black")

    out_png = out_dir / "network_pathway_comparison.png"
    canvas.save(out_png, dpi=(300, 300))
    return [out_png]


def residue_number_from_label(label: str) -> int:
    match = re.search(r"(\d+)$", label)
    if not match:
        raise ValueError(f"residue label has no residue number: {label}")
    return int(match.group(1))


def read_remodel_residue_sets(args: argparse.Namespace) -> dict[tuple[str, str], list[int]]:
    table = DATA_ROOT / "tables" / "from_run" / "network_residue_transition_frequency.csv"
    if not table.exists():
        table = DATA_ROOT / "tables" / "network_residue_transition_frequency.csv"
    table = require_file(table, "network residue-frequency table")
    rows = csv_rows(table)
    sets: dict[tuple[str, str], list[int]] = {}
    for state in ["apo", "holo"]:
        for transition_class in ["wt_lost", "gained"]:
            selected = [
                row
                for row in rows
                if row.get("state", "").lower() == state and row.get("transition_class", "").lower() == transition_class
            ]
            selected.sort(key=lambda row: (-int(float(row.get("count", 0))), residue_number_from_label(row["residue"])))
            sets[(state, transition_class)] = [
                residue_number_from_label(row["residue"]) for row in selected[: args.remodel_top_n]
            ]
            if not sets[(state, transition_class)]:
                raise SystemExit(f"no residues found for {state}/{transition_class} in {table}")
    return sets


def plus_residues(values: list[int]) -> str:
    return "+".join(str(value) for value in values) if values else "999999"


def comma_residues(values: list[int]) -> str:
    return ",".join(str(value) for value in values) if values else "999999"


def residue_sort_key(key: tuple[str, str, str, str]) -> tuple[str, int, str, str]:
    chain, resseq, icode, resname = key
    try:
        resseq_value = int(resseq)
    except ValueError:
        resseq_value = 0
    return (chain, resseq_value, icode, resname)


def parse_pdb_atoms(path: Path) -> tuple[
    list[str],
    dict[tuple[str, str, str, str], np.ndarray],
    dict[tuple[str, str, str], np.ndarray],
]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    ca_coords: dict[tuple[str, str, str, str], np.ndarray] = {}
    residue_ca_coords: dict[tuple[str, str, str], np.ndarray] = {}
    for line in lines:
        if not line.startswith(("ATOM  ", "HETATM")):
            continue
        atom_name = line[12:16].strip()
        if atom_name != "CA":
            continue
        chain = line[21].strip()
        resseq = line[22:26].strip()
        icode = line[26].strip()
        resname = line[17:20].strip()
        key = (chain, resseq, icode, resname)
        ca_coords[key] = np.array([float(line[30:38]), float(line[38:46]), float(line[46:54])], dtype=float)
        residue_ca_coords[(resseq, icode, resname)] = ca_coords[key]
    return lines, ca_coords, residue_ca_coords


def kabsch_transform(mobile: np.ndarray, reference: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    mobile_center = mobile.mean(axis=0)
    reference_center = reference.mean(axis=0)
    mobile_centered = mobile - mobile_center
    reference_centered = reference - reference_center
    covariance = mobile_centered.T @ reference_centered
    v, _s, wt = np.linalg.svd(covariance)
    correction = np.eye(3)
    correction[2, 2] = np.linalg.det(v @ wt)
    rotation = v @ correction @ wt
    translation = reference_center - mobile_center @ rotation
    return rotation, translation


def aligned_pdb_for_surface_render(pdb: Path, reference: Path | None, out_pdb: Path) -> Path:
    if reference is None:
        return pdb
    reference = require_file(reference, "residue-remodel reference PDB")
    lines, mobile_ca, mobile_residue_ca = parse_pdb_atoms(pdb)
    _reference_lines, reference_ca, reference_residue_ca = parse_pdb_atoms(reference)
    common = sorted(set(mobile_ca) & set(reference_ca), key=residue_sort_key)
    if len(common) < 20:
        residue_common = sorted(set(mobile_residue_ca) & set(reference_residue_ca), key=lambda key: residue_sort_key(("", *key)))
        mobile = np.array([mobile_residue_ca[key] for key in residue_common], dtype=float)
        reference_xyz = np.array([reference_residue_ca[key] for key in residue_common], dtype=float)
        match_count = len(residue_common)
    else:
        mobile = np.array([mobile_ca[key] for key in common], dtype=float)
        reference_xyz = np.array([reference_ca[key] for key in common], dtype=float)
        match_count = len(common)
    if match_count < 20:
        raise SystemExit(f"not enough matching CA atoms to align {pdb} to {reference}: {match_count}")
    rotation, translation = kabsch_transform(mobile, reference_xyz)

    aligned: list[str] = []
    for line in lines:
        if line.startswith(("ATOM  ", "HETATM")) and len(line) >= 54:
            xyz = np.array([float(line[30:38]), float(line[38:46]), float(line[46:54])], dtype=float)
            transformed = xyz @ rotation + translation
            line = f"{line[:30]}{transformed[0]:8.3f}{transformed[1]:8.3f}{transformed[2]:8.3f}{line[54:]}"
        aligned.append(line)
    out_pdb.parent.mkdir(parents=True, exist_ok=True)
    out_pdb.write_text("\n".join(aligned) + "\n", encoding="utf-8")
    print(f"[OK] aligned surface render input: {out_pdb} ({match_count} CA atoms)")
    return out_pdb


def render_residue_remodel_pymol(args: argparse.Namespace, sets: dict[tuple[str, str], list[int]], out_dir: Path) -> list[Path]:
    script_dir = RUN_ROOT / "pymol" / "residue_remodel"
    script_dir.mkdir(parents=True, exist_ok=True)
    pymol_dir = out_dir / "residue_remodel" / "pymol"
    pymol_dir.mkdir(parents=True, exist_ok=True)

    apo_pdb = require_file(DATA_ROOT / "prepared" / "apo" / args.wt / f"{args.wt}.pdb", "apo WT PDB")
    holo_pdb = require_file(DATA_ROOT / "prepared" / "holo" / args.wt / f"{args.wt}.pdb", "holo WT PDB")
    script = script_dir / "render_residue_remodel.py"
    write_text(
        script,
        f"""
from math import sqrt
from pymol import cmd, cgo

OUT_DIR = r"{pymol_dir.as_posix()}"
APO_PDB = r"{apo_pdb.as_posix()}"
HOLO_PDB = r"{holo_pdb.as_posix()}"
NON_PROTEIN_RESN = "ATP+ADP+AMP+MG+MG2+MGM+WAT+HOH+NA+K+CL"
KINASE_VIEW = (
    0.8545376658439636, 0.46188580989837646, 0.23754343390464783,
    -0.24071544408798218, 0.7574628591537476, -0.6068824529647827,
    -0.4602406919002533, 0.46142351627349854, 0.7584635019302368,
    0.0, 0.0, -262.4645690917969,
    44.75941848754883, 32.431861877441406, 65.35641479492188,
    206.92906188964844, 318.00006103515625, -20.0
)
ONE_LETTER = {{
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "HID": "H",
    "HIE": "H", "HIP": "H", "ILE": "I", "LEU": "L", "LYS": "K",
    "MET": "M", "PHE": "F", "PRO": "P", "SER": "S", "THR": "T",
    "TRP": "W", "TYR": "Y", "VAL": "V",
}}

def _norm(v):
    n = sqrt(v[0] ** 2 + v[1] ** 2 + v[2] ** 2)
    if n == 0:
        return (1.0, 0.0, 0.0)
    return (v[0] / n, v[1] / n, v[2] / n)

def _protein_center(selection):
    model = cmd.get_model(selection)
    coords = [atom.coord for atom in model.atom]
    return tuple(sum(coord[i] for coord in coords) / len(coords) for i in range(3))

def _add_arrow(start, end, name):
    color = (0.12, 0.12, 0.12)
    radius = 0.075
    head = 0.26
    vx, vy, vz = end[0] - start[0], end[1] - start[1], end[2] - start[2]
    n = sqrt(vx * vx + vy * vy + vz * vz)
    if n == 0:
        return
    ux, uy, uz = vx / n, vy / n, vz / n
    cone_start = (end[0] - ux * head, end[1] - uy * head, end[2] - uz * head)
    obj = [
        cgo.CYLINDER, start[0], start[1], start[2], cone_start[0], cone_start[1], cone_start[2],
        radius, color[0], color[1], color[2], color[0], color[1], color[2],
        cgo.CONE, cone_start[0], cone_start[1], cone_start[2], end[0], end[1], end[2],
        radius * 1.8, 0.0, color[0], color[1], color[2], color[0], color[1], color[2], 1.0, 0.0,
    ]
    cmd.load_cgo(obj, name)

def _label_selection(sel_name, label_color="black"):
    center = _protein_center("prot")
    model = cmd.get_model(sel_name)
    for idx, atom in enumerate(model.atom, start=1):
        ca = atom.coord
        d = _norm((ca[0] - center[0], ca[1] - center[1], ca[2] - center[2]))
        tang = _norm((-d[1], d[0], 0.0))
        side = -1.0 if idx % 2 == 0 else 1.0
        anchor = (
            ca[0] + d[0] * 12.0 + tang[0] * side * 1.8,
            ca[1] + d[1] * 12.0 + tang[1] * side * 1.8,
            ca[2] + d[2] * 12.0,
        )
        lbl = f"lbl_{{atom.resn}}{{atom.resi}}_{{idx}}"
        cmd.pseudoatom(lbl, pos=anchor)
        aa = ONE_LETTER.get(atom.resn.upper(), atom.resn[:1].upper())
        cmd.label(lbl, f'"{{aa}}{{atom.resi}}"')
        cmd.set("label_size", 16, lbl)
        cmd.set("label_color", label_color, lbl)
        cmd.hide("nonbonded", lbl)
        _add_arrow(anchor, ca, f"arr_{{atom.resn}}{{atom.resi}}_{{idx}}")

def setup_scene(obj_name):
    cmd.hide("everything", "all")
    cmd.bg_color("white")
    cmd.set("antialias", 2)
    cmd.set("ray_trace_mode", 1)
    cmd.set("ray_shadows", 0)
    cmd.set("depth_cue", 0)
    cmd.set("orthoscopic", "on")
    cmd.set("auto_zoom", 0)
    cmd.set("spec_reflect", 0.2)
    cmd.set("cartoon_fancy_helices", 1)
    cmd.set("cartoon_smooth_loops", 1)
    cmd.set("sphere_scale", 0.55)
    cmd.set("stick_radius", 0.18)
    cmd.set("label_font_id", 9)
    cmd.select("prot", f"{{obj_name}} and not resn {{NON_PROTEIN_RESN}}")
    cmd.show("cartoon", "prot")
    cmd.color("wheat", "prot")
    cmd.set("cartoon_transparency", 0.18, "prot")
    cmd.set_view(KINASE_VIEW)
    cmd.turn("z", 90)
    cmd.zoom("prot", 2.4)

def render_state(obj_name, wt_lost, gained, out_both, show_atp):
    setup_scene(obj_name)
    cmd.select("wt_lost", f"prot and name CA and resi {{wt_lost}}")
    cmd.select("gained", f"prot and name CA and resi {{gained}}")
    cmd.select("y171", "prot and resi 171 and name CA")
    cmd.show("spheres", "wt_lost")
    cmd.show("spheres", "gained")
    cmd.show("spheres", "y171")
    cmd.color("marine", "wt_lost")
    cmd.set_color("dark_orange_net", [0.92, 0.42, 0.00])
    cmd.color("dark_orange_net", "gained")
    cmd.color("magenta", "y171")
    if show_atp:
        cmd.select("atp", f"{{obj_name}} and resn ATP")
        cmd.show("sticks", "atp")
        cmd.color("green", "atp")
        cmd.set("stick_radius", 0.28, "atp")
    _label_selection("wt_lost")
    _label_selection("gained")
    if cmd.count_atoms("y171"):
        _label_selection("y171", label_color="magenta")
    cmd.ray(2100, 2400)
    cmd.png(out_both, dpi=300)

cmd.reinitialize()
cmd.load(APO_PDB, "apo")
render_state("apo", "{plus_residues(sets[('apo', 'wt_lost')])}", "{plus_residues(sets[('apo', 'gained')])}", OUT_DIR + "/apo_residue_coloring_wtlost_gained.png", False)
cmd.delete("all")
cmd.load(HOLO_PDB, "holo")
render_state("holo", "{plus_residues(sets[('holo', 'wt_lost')])}", "{plus_residues(sets[('holo', 'gained')])}", OUT_DIR + "/holo_residue_coloring_wtlost_gained.png", True)
cmd.quit()
""".strip()
        + "\n",
    )
    run_command(["pymol", "-cq", str(script)])
    paths = [
        pymol_dir / "apo_residue_coloring_wtlost_gained.png",
        pymol_dir / "holo_residue_coloring_wtlost_gained.png",
    ]
    return crop_pngs(paths, padding_x=40, padding_top=24, padding_bottom=40)


def render_residue_remodel_chimerax(args: argparse.Namespace, sets: dict[tuple[str, str], list[int]], out_dir: Path) -> list[Path]:
    if not shutil_which("chimerax"):
        print("[INFO] chimerax not found; skipping surface panels.")
        return []
    script_dir = RUN_ROOT / "chimerax" / "residue_remodel"
    script_dir.mkdir(parents=True, exist_ok=True)
    surface_dir = out_dir / "residue_remodel" / "chimerax"
    surface_dir.mkdir(parents=True, exist_ok=True)
    references = {
        "apo": Path(args.remodel_apo_reference).expanduser() if args.remodel_apo_reference else None,
        "holo": Path(args.remodel_holo_reference).expanduser() if args.remodel_holo_reference else None,
    }
    panels: list[Path] = []
    for state, title, pdb in [
        ("apo", "apo_surface", DATA_ROOT / "prepared" / "apo" / args.wt / f"{args.wt}.pdb"),
        ("holo", "holo_surface", DATA_ROOT / "prepared" / "holo" / args.wt / f"{args.wt}.pdb"),
    ]:
        pdb = require_file(pdb, f"{state} WT PDB")
        pdb = aligned_pdb_for_surface_render(pdb, references[state], script_dir / "aligned" / f"{title}.pdb")
        out_png = surface_dir / f"{title}.png"
        cxc = script_dir / f"{title}.cxc"
        atp_block = ""
        if state == "holo":
            atp_block = """
show #1:ATP atoms
style #1:ATP stick
color #1:ATP green
size stickRadius 0.28
"""
        write_text(
            cxc,
            f"""
open {pdb.as_posix()}
hide atoms
surface #1 & protein
color #1 & protein wheat target s
transparency #1 & protein 18 target s
color #1:{comma_residues(sets[(state, 'wt_lost')])} blue target s
color #1:{comma_residues(sets[(state, 'gained')])} orangered target s
color #1:171 magenta target s
{atp_block}
set bgColor white
lighting full
graphics silhouettes true
view matrix camera -0.31169,0.79727,0.51692,212.61,-0.87489,-0.028557,-0.48348,-118.97,-0.37071,-0.60294,0.70642,283.72 models #1,1,0,0,0,0,1,0,0,0,0,1,0
zoom 1.92
save {out_png.as_posix()} width 1400 height 1600 supersample 3
exit
""".strip()
            + "\n",
        )
        chimerax_env = os.environ.copy()
        chimerax_env.update(
            {
                "XDG_DATA_HOME": "/tmp/chimerax-data",
                "XDG_CONFIG_HOME": "/tmp/chimerax-config",
                "XDG_CACHE_HOME": "/tmp/chimerax-cache",
                "HOME": "/tmp/chimerax-home",
            }
        )
        subprocess.run(["chimerax", "--nogui", "--offscreen", "--silent", str(cxc)], check=True, env=chimerax_env)
        panels.append(out_png)
    return crop_pngs(panels, padding_x=28, padding_top=22, padding_bottom=28)


def content_bbox_image(img, white_cutoff: int = 248) -> tuple[int, int, int, int]:
    rgb = img.convert("RGB")
    arr = np.array(rgb)
    mask = np.any(arr < white_cutoff, axis=2)
    if not mask.any():
        return (0, 0, img.width, img.height)
    ys, xs = np.where(mask)
    return (int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1)


def crop_pngs(paths: list[Path], padding_x: int, padding_top: int, padding_bottom: int) -> list[Path]:
    from PIL import Image

    outputs: list[Path] = []
    for path in paths:
        img = Image.open(path)
        left, top, right, bottom = content_bbox_image(img)
        left = max(0, left - padding_x)
        top = max(0, top - padding_top)
        right = min(img.width, right + padding_x)
        bottom = min(img.height, bottom + padding_bottom)
        out = path.with_name(path.stem + "_cropped.png")
        img.crop((left, top, right, bottom)).save(out)
        outputs.append(out)
    return outputs


def png_size(path: Path) -> tuple[int, int]:
    with path.open("rb") as handle:
        handle.read(8)
        length = struct.unpack(">I", handle.read(4))[0]
        handle.read(4)
        data = handle.read(length)
    return struct.unpack(">II", data[:8])


def embed_png(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def assemble_residue_remodel_figure(out_dir: Path, surface_paths: list[Path]) -> list[Path]:
    from PIL import Image, ImageDraw, ImageFont

    remodel_dir = out_dir / "residue_remodel"
    panels = [
        ("A", remodel_dir / "pymol" / "apo_residue_coloring_wtlost_gained_cropped.png", "cartoon"),
        ("B", remodel_dir / "chimerax" / "apo_surface_cropped.png", "surface"),
        ("C", remodel_dir / "pymol" / "holo_residue_coloring_wtlost_gained_cropped.png", "cartoon"),
        ("D", remodel_dir / "chimerax" / "holo_surface_cropped.png", "surface"),
    ]
    if not surface_paths:
        panels = [panels[0], panels[2]]

    panel_sizes = []
    for _letter, path, kind in panels:
        w, h = png_size(require_file(path, "residue-remodel panel"))
        target_h = 900 if kind == "cartoon" else 640
        panel_sizes.append((round(target_h * (w / h)), target_h))

    margin_x = 6
    margin_top = 18
    margin_bottom = 12
    gutter_x = 4
    label_h = 22
    legend_h = 26
    legend_gap = 8
    panel_label_size = 32
    legend_size = 32
    legend_radius = 11
    row_h = max(h for _w, h in panel_sizes)
    canvas_w = margin_x * 2 + sum(w for w, _h in panel_sizes) + gutter_x * (len(panels) - 1)
    canvas_h = margin_top + label_h + row_h + legend_gap + legend_h + margin_bottom
    y = margin_top + label_h
    font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    try:
        panel_font = ImageFont.truetype(font_path, panel_label_size)
        legend_font = ImageFont.truetype(font_path, legend_size)
    except OSError:
        panel_font = ImageFont.load_default()
        legend_font = ImageFont.load_default()

    parts = [
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="{canvas_w}" height="{canvas_h}" viewBox="0 0 {canvas_w} {canvas_h}">',
        '  <rect width="100%" height="100%" fill="#ffffff"/>',
    ]
    png_canvas = Image.new("RGB", (canvas_w, canvas_h), "white")
    png_draw = ImageDraw.Draw(png_canvas)
    x = margin_x
    for index, (letter, path, _kind) in enumerate(panels):
        panel_w, panel_h = panel_sizes[index]
        panel_y = y + (row_h - panel_h) / 2
        parts.append(
            f'  <image x="{x:.1f}" y="{panel_y:.1f}" width="{panel_w}" height="{panel_h}" '
            f'xlink:href="data:image/png;base64,{embed_png(path)}" />'
        )
        parts.append(
            f'  <text x="{x + 6:.1f}" y="{y + 22}" font-family="DejaVu Sans, Arial, sans-serif" '
            f'font-size="32" font-weight="400" fill="#111111">{letter}</text>'
        )
        panel_img = Image.open(path).convert("RGB")
        resampling = getattr(Image, "Resampling", None)
        panel_img = panel_img.resize((panel_w, panel_h), resampling.LANCZOS if resampling else 1)
        png_canvas.paste(panel_img, (round(x), round(panel_y)))
        png_draw.text((x + 6, y - 11), letter, font=panel_font, fill="#111111")
        x += panel_w + gutter_x

    legend_y = y + row_h + legend_gap + 8
    legend_cx = canvas_w / 2
    legend = [(-300, "#0057d8", "WT-lost"), (-80, "#e65100", "Gained"), (140, "#cc00cc", "Y171"), (320, "#1b8f3a", "ATP")]
    for offset, color, label in legend:
        lx = legend_cx + offset
        parts.append(f'  <circle cx="{lx}" cy="{legend_y}" r="{legend_radius}" fill="{color}"/>')
        parts.append(
            f'  <text x="{lx + 20}" y="{legend_y + 10}" font-family="DejaVu Sans, Arial, sans-serif" '
            f'font-size="32" font-weight="400" fill="#111111">{label}</text>'
        )
        png_draw.ellipse(
            (
                lx - legend_radius,
                legend_y - legend_radius,
                lx + legend_radius,
                legend_y + legend_radius,
            ),
            fill=color,
        )
        png_draw.text((lx + 20, legend_y - 20), label, font=legend_font, fill="#111111")
    parts.append("</svg>")

    svg = out_dir / "network_residue_remodel.svg"
    svg.write_text("\n".join(parts), encoding="utf-8")
    png = out_dir / "network_residue_remodel.png"
    png_canvas.save(png, dpi=(300, 300))
    return [svg, png]


def build_residue_remodel_figure(args: argparse.Namespace, out_dir: Path) -> list[Path]:
    if args.state != "all" or args.summary_only or args.skip_remodel:
        return []
    if not shutil_which("pymol"):
        print("[INFO] pymol not found; skipping residue-remodel figure.")
        return []
    sets = read_remodel_residue_sets(args)
    pymol_paths = render_residue_remodel_pymol(args, sets, out_dir)
    surface_paths = render_residue_remodel_chimerax(args, sets, out_dir)
    written = [*pymol_paths, *surface_paths]
    written += assemble_residue_remodel_figure(out_dir, surface_paths)
    return written


def write_network_tables(args: argparse.Namespace) -> None:
    out_dir = Path(args.outdir).expanduser() if args.outdir else DATA_ROOT / "tables" / "from_run"
    apo_overlap = require_file(DATA_ROOT / "compare" / "apo" / "overlap_with_WT.csv", "apo overlap table")
    holo_overlap = require_file(DATA_ROOT / "compare" / "holo" / "overlap_with_WT.csv", "holo overlap table")
    apo_frequency = require_file(DATA_ROOT / "compare" / "apo" / "transition_frequency.csv", "apo transition-frequency table")
    holo_frequency = require_file(DATA_ROOT / "compare" / "holo" / "transition_frequency.csv", "holo transition-frequency table")

    apo_by_variant = {row["variant"]: row for row in csv_rows(apo_overlap)}
    holo_by_variant = {row["variant"]: row for row in csv_rows(holo_overlap)}
    overlap_rows: list[dict[str, object]] = []
    for variant in sorted(set(apo_by_variant) | set(holo_by_variant)):
        apo = apo_by_variant.get(variant, {})
        holo = holo_by_variant.get(variant, {})
        overlap_rows.append(
            {
                "variant": variant,
                "apo_shared": apo.get("shared", ""),
                "apo_shared_fraction": apo.get("shared_fraction", ""),
                "apo_wt_lost": apo.get("wt_lost", ""),
                "apo_gained": apo.get("gained", ""),
                "holo_shared": holo.get("shared", ""),
                "holo_shared_fraction": holo.get("shared_fraction", ""),
                "holo_wt_lost": holo.get("wt_lost", ""),
                "holo_gained": holo.get("gained", ""),
            }
        )
    overlap_out = out_dir / "network_overlap_apo_vs_holo.csv"
    write_csv(
        overlap_out,
        overlap_rows,
        [
            "variant",
            "apo_shared",
            "apo_shared_fraction",
            "apo_wt_lost",
            "apo_gained",
            "holo_shared",
            "holo_shared_fraction",
            "holo_wt_lost",
            "holo_gained",
        ],
    )

    frequency_rows: list[dict[str, object]] = []
    for source, state_label in [(apo_frequency, "apo"), (holo_frequency, "holo")]:
        for row in csv_rows(source):
            frequency_rows.append(
                {
                    "state": state_label,
                    "transition_class": row["transition_class"],
                    "residue": row["residue"],
                    "count": row["count"],
                    "total_variants": row["total_variants"],
                }
            )
    frequency_out = out_dir / "network_residue_transition_frequency.csv"
    write_csv(
        frequency_out,
        frequency_rows,
        ["state", "transition_class", "residue", "count", "total_variants"],
    )

    print(f"[OK] network table: {overlap_out}")
    print(f"[OK] network table: {frequency_out}")


def check_prepared_frames(args: argparse.Namespace) -> None:
    try:
        import MDAnalysis as mda
    except ImportError as exc:
        raise SystemExit(f"missing MDAnalysis for frame check: {exc}") from exc

    variants = array_variants(args)
    prepared_root = network_data_root() / "prepared" / args.state
    required_frames = args.num_sampled_frames + 1
    failures = 0
    for variant in variants:
        dcd = prepared_root / variant / f"{variant}.dcd"
        if not dcd.exists():
            print(f"FAIL {args.state}/{variant}: missing prepared DCD {dcd}")
            failures += 1
            continue
        frames = len(mda.Universe(str(dcd)).trajectory)
        status = "OK" if frames >= required_frames else "FAIL"
        print(
            f"{status} {args.state}/{variant}: frames={frames}, "
            f"required>={required_frames}, dcd={dcd}"
        )
        if status != "OK":
            failures += 1
    if failures:
        raise SystemExit(f"{failures} variants are not ready for {args.num_sampled_frames} sampled frames")


def render_structure_path(state: str, variant: str, wt: str, pdb_arg: str | None = None) -> Path:
    if pdb_arg:
        return Path(pdb_arg).expanduser()
    variant_pdb = DATA_ROOT / "prepared" / state / variant / f"{variant}.pdb"
    if variant_pdb.exists():
        return variant_pdb
    wt_pdb = DATA_ROOT / "prepared" / state / wt / f"{wt}.pdb"
    if wt_pdb.exists():
        print(f"[WARN] missing variant structure {variant_pdb}; using WT structure {wt_pdb}")
        return wt_pdb
    raise SystemExit(f"missing render structure: {variant_pdb}")


def render_pymol(args: argparse.Namespace) -> None:
    table = DATA_ROOT / "compare" / args.state / "wt_vs_variants_lost_gained.csv"
    groups = {"shared": [], "wt_lost": [], "gained": []}
    for row in csv_rows(table):
        if row["variant"] == args.variant:
            groups[row["transition_class"]].append(row["residue_number"])

    def plus(values: list[str]) -> str:
        return "+".join(values) if values else "999999"

    pdb = render_structure_path(args.state, args.variant, args.wt, getattr(args, "pdb", None))
    out_dir = DATA_ROOT / "render" / args.state
    out_dir.mkdir(parents=True, exist_ok=True)
    pml = out_dir / f"{args.variant}_network_residues.pml"
    png = out_dir / f"{args.variant}_network_residues.png"
    write_text(
        pml,
        f"""
load {pdb}, cdkl5
hide everything
bg_color white
set ray_shadows, 0
set orthoscopic, on
select prot, cdkl5 and polymer.protein
show cartoon, prot
color wheat, prot
set cartoon_transparency, 0.15
select shared, prot and name CA and resi {plus(groups['shared'])}
select wt_lost, prot and name CA and resi {plus(groups['wt_lost'])}
select gained, prot and name CA and resi {plus(groups['gained'])}
show spheres, shared
show spheres, wt_lost
show spheres, gained
color forest, shared
color marine, wt_lost
set_color varmdyn_orange, [0.92, 0.42, 0.00]
color varmdyn_orange, gained
set sphere_scale, 0.65
zoom prot, 3
ray 1600, 1200
png {png}, dpi=300
quit
""",
    )
    run_command(["pymol", "-cq", str(pml)])
    print(f"[OK] rendered: {png}")


def run_full(args: argparse.Namespace) -> None:
    states = ["apo", "holo"] if args.state == "all" else [args.state]
    for state in states:
        root = args.apo_root if state == "apo" else args.holo_root
        if not root:
            raise SystemExit(f"set --{state}-root or VARMDYN_{state.upper()}_ROOT")
        state_args = argparse.Namespace(**vars(args))
        state_args.state = state
        state_args.root = root
        variants = resolve_variants(state_args)
        print(f"[INFO] state={state}")
        print(f"[INFO] variants={','.join(variants)}")
        for variant in variants:
            prepare_variant(state_args, variant)
        for variant in variants:
            run_dynetan_variant(state_args, variant)
        compare_top25(state_args)
        render_variant = args.render_variant or next((variant for variant in variants if variant != args.wt), "")
        if render_variant and args.render:
            render_args = argparse.Namespace(**vars(state_args))
            render_args.variant = render_variant
            render_args.pdb = None
            if shutil_which("pymol"):
                render_pymol(render_args)
            else:
                print("[INFO] pymol not found; skipping render.")


def shutil_which(name: str) -> str | None:
    from shutil import which

    return which(name)


def state_md_root(state: str, root_arg: str | None = None) -> Path:
    if root_arg:
        return Path(root_arg).expanduser()
    source_root = os.environ.get("VARMDYN_MD_SOURCE_ROOT")
    if source_root:
        return Path(source_root).expanduser() / state
    state_env = os.environ.get(f"VARMDYN_{state.upper()}_ROOT")
    if state_env:
        return Path(state_env).expanduser()
    return REPO_ROOT / "data" / "md" / state


def network_data_root() -> Path:
    configured = os.environ.get("VARMDYN_NETWORK_DATA_ROOT")
    if configured:
        return Path(configured).expanduser()
    mdan_root = os.environ.get("VARMDYN_MDAN_OUTPUT_ROOT")
    if mdan_root:
        return Path(mdan_root).expanduser() / "network"
    return DATA_ROOT


def network_run_root() -> Path:
    configured = os.environ.get("VARMDYN_NETWORK_RUN_ROOT")
    if configured:
        return Path(configured).expanduser()
    return network_data_root() / "runs"


def array_variants(args: argparse.Namespace) -> list[str]:
    state_root = state_md_root(args.state, args.root)
    plan_args = argparse.Namespace(
        root=str(state_root),
        wt=args.wt,
        variants="" if variants_arg_requests_all(args.variants) else args.variants,
        topology_suffix=args.topology_suffix,
    )
    return resolve_variants(plan_args)


def array_plan(args: argparse.Namespace) -> None:
    state_root = state_md_root(args.state, args.root)
    variants = array_variants(args)
    print(f"state={args.state}")
    print(f"md_root={state_root}")
    print(f"out_root={network_data_root()}")
    print(f"run_root={network_run_root()}")
    print(f"variants={','.join(variants)}")
    print(f"array=0-{len(variants) - 1}")
    print("stages=prepare,run,compare")
    print(f"topology=<md-root>/<state>/<variant>/{args.topology_suffix}")
    print(f"trajectories=<md-root>/<state>/<variant>/{args.traj_template}")
    print("outputs=network/prepared/<state>/<variant>,network/dynetan/<state>/<variant>,network/compare/<state>")


def sbatch_env(args: argparse.Namespace, variants: list[str]) -> dict[str, str]:
    state_root = state_md_root(args.state, args.root)
    env = {
        "VARMDYN_NETWORK_DATA_ROOT": str(network_data_root()),
        "VARMDYN_NETWORK_RUN_ROOT": str(network_run_root()),
        f"VARMDYN_{args.state.upper()}_ROOT": str(state_root),
        "VARMDYN_VARIANTS": ":".join(variants),
        "VARMDYN_WT": args.wt,
        "VARMDYN_TOPOLOGY_SUFFIX": args.topology_suffix,
        "VARMDYN_TRAJ_TEMPLATE": args.traj_template,
        "VARMDYN_REPLICAS": slurm_list_value(args.replicas),
        "VARMDYN_CHUNKS": slurm_list_value(args.chunks),
        "VARMDYN_STRIDE": str(args.stride),
    }
    if args.stage_tag:
        env["VARMDYN_DYNETAN_STAGE_TAG"] = args.stage_tag
    if args.dynetan_env:
        env["VARMDYN_DYNETAN_ENV"] = args.dynetan_env
    if args.allow_short_sample:
        env["VARMDYN_ALLOW_SHORT_SAMPLE"] = "1"
    return env


def run_capture_stdout(cmd: list[str]) -> str:
    proc = subprocess.run(cmd, text=True, capture_output=True, check=False)
    if proc.stdout:
        print(proc.stdout.strip())
    if proc.stderr:
        print(proc.stderr.strip())
    if proc.returncode:
        raise SystemExit(proc.returncode)
    return proc.stdout.strip()


def parse_job_id(text: str) -> str:
    first = text.strip().splitlines()[-1] if text.strip() else ""
    match = re.search(r"(\d+)(?:\D|$)", first)
    if not match:
        raise SystemExit(f"could not parse Slurm job id from: {text!r}")
    return match.group(1)


def array_submit(args: argparse.Namespace) -> None:
    variants = array_variants(args)
    if not variants:
        raise SystemExit("no variants selected")
    env = sbatch_env(args, variants)
    env_prefix = ",".join(f"{key}={value}" for key, value in env.items())
    script = "workflows/mdan/network/run_network_array.slurm"
    log_dir = network_run_root() / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    stdout = str(log_dir / "network_array_%A_%a.out")
    stderr = str(log_dir / "network_array_%A_%a.err")
    print(f"[INFO] state={args.state}")
    print(f"[INFO] variants={','.join(variants)}")
    print(f"[INFO] network_data_root={network_data_root()}")
    print(f"[INFO] network_log_root={log_dir}")
    variant_cmd = [
        "sbatch",
        "--parsable",
        f"--array=0-{len(variants) - 1}",
        f"--output={stdout}",
        f"--error={stderr}",
        "--export=ALL," + env_prefix,
        script,
        args.state,
        "variant",
    ]
    variant_job = parse_job_id(run_capture_stdout(variant_cmd))
    compare_cmd = [
        "sbatch",
        "--parsable",
        f"--dependency=afterok:{variant_job}",
        f"--output={stdout}",
        f"--error={stderr}",
        "--export=ALL," + env_prefix,
        script,
        args.state,
        "compare",
    ]
    compare_job = parse_job_id(run_capture_stdout(compare_cmd))
    LAST_HPC_JOB_FILE.write_text(compare_job + "\n", encoding="utf-8")
    print(f"[OK] submitted network variant array {variant_job} and compare job {compare_job}")


def array_status(args: argparse.Namespace) -> None:
    job_id = resolve_array_job_id(args.job_id)
    if job_id:
        queue_cmd = ["squeue", "-j", job_id]
        acct_cmd = ["sacct", "-j", job_id, "--format=JobID,JobName,State,ExitCode,Elapsed,Start,End"]
    else:
        user = os.environ.get("USER", "")
        queue_cmd = ["squeue", "-u", user]
        acct_cmd = [
            "sacct",
            "-u",
            user,
            "--starttime",
            "now-2days",
            "--format=JobID,JobName,State,ExitCode,Elapsed,Start,End",
        ]
    run_command(queue_cmd)
    run_command(acct_cmd)


def resolve_array_job_id(job_id: str | None, *, required: bool = False) -> str | None:
    if job_id:
        return job_id
    if LAST_HPC_JOB_FILE.exists():
        recorded = LAST_HPC_JOB_FILE.read_text(encoding="utf-8").strip()
        if recorded:
            return recorded
    if required:
        raise SystemExit("--job-id is required because no previous network job id is recorded")
    return None


def add_common(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--state", choices=["apo", "holo"], required=True)
    parser.add_argument("--root", required=True)
    parser.add_argument("--variants", default=os.environ.get("VARMDYN_VARIANTS", ""))
    parser.add_argument("--wt", default=os.environ.get("VARMDYN_WT", "01_WT"))


def add_prep(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--topology-suffix", default="02.leap/com/cdl.com.wat.leap.prmtop")
    parser.add_argument("--traj-template", default="03.pmemd/com/{replica}/{chunk}md.mdcrd.nc")
    parser.add_argument("--replicas", default="cr1,cr2,cr3")
    parser.add_argument("--chunks", default="25,26,27,28,29")
    parser.add_argument("--stride", type=int, default=20)
    parser.add_argument("--apo-strip-mask", default=":WAT,Na+,Cl-")
    parser.add_argument("--holo-strip-mask", default=":WAT,Na+,Cl-,ATP,MG")
    parser.add_argument("--min-prepared-frames", type=int, default=int(os.environ.get("VARMDYN_MIN_PREPARED_FRAMES", "751")))
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--force", action="store_true")


def add_dynetan(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--stage-tag")
    parser.add_argument("--num-winds", type=int, default=1)
    parser.add_argument("--num-sampled-frames", type=int, default=750)
    parser.add_argument("--cutoff", type=float, default=4.5)
    parser.add_argument("--contact-persistence", type=float, default=0.75)
    parser.add_argument("--ncores", type=int, default=int(os.environ.get("VARMDYN_NCORES", "8")))
    parser.add_argument("--top-nodes", type=int, default=25)
    parser.add_argument("--top-edges", type=int, default=100)
    parser.add_argument("--cartesian-backend", default="openmp")
    parser.add_argument("--allow-short-sample", action="store_true")


def add_array_common(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--state", choices=["apo", "holo"], required=True)
    parser.add_argument("--root", help="HPC-visible state root; defaults to VARMDYN_MD_SOURCE_ROOT/<state>")
    parser.add_argument("--variants", default=os.environ.get("VARMDYN_VARIANTS", "all"))
    parser.add_argument("--wt", default=os.environ.get("VARMDYN_WT", "WT"))
    parser.add_argument("--topology-suffix", default=os.environ.get("VARMDYN_TOPOLOGY_SUFFIX", "02.leap/com/cdl.com.wat.leap.prmtop"))
    parser.add_argument("--traj-template", default=os.environ.get("VARMDYN_TRAJ_TEMPLATE", "03.pmemd/com/{replica}/{chunk}md.mdcrd.nc"))
    parser.add_argument("--replicas", default=os.environ.get("VARMDYN_REPLICAS", "cr1,cr2,cr3"))
    parser.add_argument("--chunks", default=os.environ.get("VARMDYN_CHUNKS", "25,26,27,28,29"))
    parser.add_argument("--stride", type=int, default=int(os.environ.get("VARMDYN_STRIDE", "20")))
    parser.add_argument("--stage-tag", default=os.environ.get("VARMDYN_DYNETAN_STAGE_TAG", ""))
    parser.add_argument("--dynetan-env", default=os.environ.get("VARMDYN_DYNETAN_ENV", ""))
    parser.add_argument("--allow-short-sample", action="store_true")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("prepare")
    add_common(p)
    add_prep(p)

    p = sub.add_parser("run")
    add_common(p)
    add_dynetan(p)
    p.add_argument("--force", action="store_true")

    p = sub.add_parser("compare")
    add_common(p)
    p.add_argument("--stage-tag")

    p = sub.add_parser("figures")
    p.add_argument("--state", choices=["apo", "holo", "all"], default="all")
    p.add_argument("--outdir")
    p.add_argument("--top-n", type=int, default=12)
    p.add_argument("--pathway-top-n", type=int, default=25)
    p.add_argument("--variants", default=os.environ.get("VARMDYN_VARIANTS", "WT,L119R,D193H,G202E,Q219K,C291Y"))
    p.add_argument("--wt", default=os.environ.get("VARMDYN_WT", "WT"))
    p.add_argument("--summary-only", action="store_true", help="Build only CSV summary plots; skip PyMOL pathway renders.")
    p.add_argument("--force-pathways", action="store_true", help="Regenerate pathway render PNGs even if they already exist.")
    p.add_argument("--remodel-top-n", type=int, default=6, help="Top recurrent residues per state/class for the structural residue-remodel figure.")
    p.add_argument(
        "--remodel-apo-reference",
        default=os.environ.get("VARMDYN_NETWORK_REMODEL_APO_REFERENCE"),
        help="Optional apo PDB used only to align the temporary ChimeraX surface-render input.",
    )
    p.add_argument(
        "--remodel-holo-reference",
        default=os.environ.get("VARMDYN_NETWORK_REMODEL_HOLO_REFERENCE"),
        help="Optional holo PDB used only to align the temporary ChimeraX surface-render input.",
    )
    p.add_argument("--skip-remodel", action="store_true", help="Skip the structural residue-remodel figure.")

    p = sub.add_parser("tables")
    p.add_argument("--outdir")

    p = sub.add_parser("check-frames")
    add_array_common(p)
    p.add_argument("--num-sampled-frames", type=int, default=750)

    p = sub.add_parser("render")
    p.add_argument("--state", choices=["apo", "holo"], required=True)
    p.add_argument("--variant", default=os.environ.get("VARMDYN_RENDER_VARIANT", "02_L119R"))
    p.add_argument("--wt", default=os.environ.get("VARMDYN_WT", "01_WT"))
    p.add_argument("--pdb")

    p = sub.add_parser("full")
    p.add_argument("--state", choices=["apo", "holo", "all"], default="apo")
    p.add_argument("--apo-root", default=os.environ.get("VARMDYN_APO_ROOT", ""))
    p.add_argument("--holo-root", default=os.environ.get("VARMDYN_HOLO_ROOT", ""))
    p.add_argument("--variants", default=os.environ.get("VARMDYN_VARIANTS", ""))
    p.add_argument("--wt", default=os.environ.get("VARMDYN_WT", "01_WT"))
    p.add_argument("--render-variant", default=os.environ.get("VARMDYN_RENDER_VARIANT", ""))
    p.add_argument("--render", action="store_true")
    add_prep(p)
    add_dynetan(p)

    p = sub.add_parser("array-plan")
    add_array_common(p)
    p = sub.add_parser("array-submit")
    add_array_common(p)
    p = sub.add_parser("array-status")
    p.add_argument("--state", choices=["apo", "holo"], help="Accepted for wrapper symmetry; status is selected by job id.")
    p.add_argument("--job-id")

    args = parser.parse_args()
    if args.command == "prepare":
        for variant in resolve_variants(args):
            prepare_variant(args, variant)
    elif args.command == "run":
        for variant in resolve_variants(args):
            run_dynetan_variant(args, variant)
    elif args.command == "compare":
        compare_top25(args)
    elif args.command == "figures":
        build_figures(args)
    elif args.command == "tables":
        write_network_tables(args)
    elif args.command == "check-frames":
        check_prepared_frames(args)
    elif args.command == "render":
        render_pymol(args)
    elif args.command == "full":
        run_full(args)
    elif args.command == "array-plan":
        array_plan(args)
    elif args.command == "array-submit":
        array_submit(args)
    elif args.command == "array-status":
        array_status(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
