#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKFLOW="$ROOT/workflows/mdan/dynamics"
OUTDIR="${OUTDIR:-${VARMDYN_RUN_ROOT:-$ROOT/runs}/mdan/dynamics}"
DATA_ROOT="${VARMDYN_DATA_ROOT:-$ROOT/data}"
INPUT_ROOT="${DYNAMICS_NLOBE_Y171_INPUT_ROOT:-$DATA_ROOT/dynamics}"

missing=0
for subdir in nlobe_apo nlobe_holo y171_apo y171_holo; do
  if [[ ! -d "$INPUT_ROOT/kept_tsvs/$subdir" ]]; then
    echo "[MISSING] $INPUT_ROOT/kept_tsvs/$subdir" >&2
    missing=1
  fi
done

if [[ "$missing" -ne 0 ]]; then
  cat >&2 <<EOF2

The local dynamics wrapper needs kept-TSV inputs. Put them under:

  $INPUT_ROOT/kept_tsvs/{nlobe_apo,nlobe_holo,y171_apo,y171_holo}/

or set DYNAMICS_NLOBE_Y171_INPUT_ROOT to a folder with that layout.
These TSVs are generated by the HPC replay and are intentionally not tracked.
EOF2
  exit 2
fi

mkdir -p "$OUTDIR/panels_ijkl"

DYNAMICS_NLOBE_Y171_GRID_NLOBE_APO="$INPUT_ROOT/kept_tsvs/nlobe_apo" \
DYNAMICS_NLOBE_Y171_GRID_NLOBE_HOLO="$INPUT_ROOT/kept_tsvs/nlobe_holo" \
DYNAMICS_NLOBE_Y171_GRID_Y171_APO="$INPUT_ROOT/kept_tsvs/y171_apo" \
DYNAMICS_NLOBE_Y171_GRID_Y171_HOLO="$INPUT_ROOT/kept_tsvs/y171_holo" \
DYNAMICS_NLOBE_Y171_OUT_DIR="$OUTDIR/panels_ijkl" \
MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp/varmdyn-matplotlib}" \
  python "$WORKFLOW/scripts/build_displacement.py"

echo "[OK] displacement panel: $OUTDIR/panels_ijkl/panels_ijkl_displacement.png"
